include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false # Documentation with '///'
    always_use_package_imports: false # Prefer relative imports
    prefer_relative_imports: true # Prefer relative imports
    sort_pub_dependencies: false # Organize in alphabetical order

